version: '3.0'

services:
  grafana:
    container_name: 'digrich-bubblechart-panel'
    platform: 'linux/amd64'
    environment:
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/dashboard.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/digrich-bubblechart-panel
      - ./provisioning:/etc/grafana/provisioning
